services:
  grenadier:
    build:
      context: .
      dockerfile: dockerfile
    container_name: zchf_grenadier
    ports:
      - "8080:8080"
    volumes:
      - grenadier_data:/data
    environment:
      - GRENADIER_BIND=0.0.0.0
    restart: unless-stopped

volumes:
  grenadier_data: